language: ruby
rvm:
 - 2.0.0
 - 2.1.2
env:
  - DB=sqlite
script:
 - RAILS_ENV=test bundle exec rake db:create db:migrate
 - bundle exec rspec spec
before_install:
 - gem update --system
 - gem --version
